version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
      node:
        version: 8
      environment:
        PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
    steps:
      - checkout
      - run: echo "A first hello"
