version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy:
    machine:
      enabled: true
    #docker:
    #  - image: circleci/python:3.6.5
    steps:
      - checkout      
      - run: sudo pip install mkdocs
      - run:
          command: ./scripts/deploy-ghpages.sh build
      
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: circleci-20-test
           
