version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test

  deploy:
    docker: circleci/python:2.7.15-stretch-node-browsers-legacy
    steps:
      - checkout      
      - run: pip install mkdocs
      - run: mkdocs gh-deploy
     
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: circleci-20-test
