version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  deploy:
    docker:
      - image: circleci/python:3.6.5
    working_directory: ~/circleci-docs-deploy
    steps:
      - checkout      
      #- run: sudo pip install mkdocs
      - run:
          command: pwd && ls -la
      - run:
          command: ~/circleci-docs-deploy/.circleci/scripts/deploy-ghpages.sh docs
      
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - deploy
#      - build
#      - test:
#          requires:
#            - build
#      - deploy:
#          requires:
#            - test
#          filters:
#            branches:
#              only: circleci-20-test
           
